### ISSUE TITLE
Link to respo on the homepage?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [privacore/open-source-search-engine#34]
I have been using findx for awhile now. So far I am liking it a lot better then DuckDuckGo and Gigablast. However, I had a little issue trying to find this respo and required me to do some searching. It would be nice if you could add a link on the homepage of the search engine that leads to this respo.

When I say homepage, I mean this page: https://www.findx.com/ Like right under where it says "We don't know what you did last summer" would be a good place.

**Comment by martinvahi** [comment]
I wasn't even aware of the findix.com and privacore.com domains. 
I find the opening post at this thread very useful.

If You (at privacore.com/findix.com) wish, then You may add 
[my list of search engine seeds](https://github.com/martinvahi/mmmv_notes/tree/master/mmmv_notes/search_engine_seeds)
to Your crawler search list. I tend to update that list from time to time,
so You may want to use some diff script to check, whether my version at GitHub has changed.

The URLs that I remove from my list tend to be broken or
changed to something that it wasn't before. So, You'll probably 
need some scripts to analyse, what to take and what to leave out
of Your own list of seeds.

The list of seed-URLs is in public domain and as of 2017 it  
contains mostly political activism related web sites, some philosophy 
related web sites and physics, math, IT, chemistry, biology related
academic sites with a lot of PDF-files.

**Comment by ROCKNROLLKID** [comment]
You should make a PR for that as this isn't related to my issue/suggestion.

**Comment by martinvahi** [comment]
As a side note I add that the [privacy by design principles](https://www.privacore.com/privacy/privacy-by-design/) _([archival copy](https://archive.is/aIaE7))_ 
look nice, but there is the risk that the moment Your 
investors want to extract their investment 
with a fat margin _(the business-speak term is "to make an exit")_
by selling the start-up company either at stock market ("public offering")
or to sell it to some other company or "venture capital fund", 
**the privacy-first-profit-second game IS OVER**, because 
by "law"_(read: demands of the supermafia, generally called "the State")_,
the CEO's of a publicly traded company are required to 
put the monetary profits of the owners of the company before
anything else. 

The [Oracle versus Google](https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.) case demonstrates 
that a pretty decent company like the [former Sun Microsystems](https://en.wikipedia.org/wiki/Sun_Microsystems)
can be bought by a nasty litigator and [open source collaboration destroyer](https://www.networkworld.com/article/2227693/opensource-subnet/apache-to-oracle--we-re-leaving-the-java-community-process.html)_([an upstream post](https://blogs.apache.org/foundation/entry/statement_by_the_asf_board1))_,
which is to say, being open source helps a lot, but business wise
You probably have to be very careful, what You promise, because
the "laws" currently only "protect" physical environment from pollution,
but **not the social environment from exploitation.**

**Comment by martinvahi** [comment]
> You should make a PR for that as this isn't related to my issue/suggestion.

Thanks, but the pull request is a kind of one-time thing. 
They should write a script that automatically downloads the list from 
GitHub whenever they want updates. Neither am I the only person
on this planet, from whom they might want to regularly download
a list of URLs.

But, again, thank You for the kind suggestion :-)

**Comment by martinvahi** [comment]
One more index seeds related related link:
[commoncrawl.org](http://commoncrawl.org/)

**Comment by br-privacore** [comment]
@ROCKNROLLKID : Thank you for the suggestion. We'll add a link in the footer in one of the next releases.

@martinvahi : thank you for the offer, but we have more than 2 billion pages in the index already, and much more than 10x that waiting to be crawled

**Comment by martinvahi** [comment]
@br-privacore  Thank You for Your answer.

>  we have more than 2 billion pages in the index already, and much more than 10x that waiting to be crawled

After some experimentation [I came to a conclusiong](https://martin.softf1.com/g/yellow_soap_opera_blog/some-thoughts-about-personalized-web-search-episode-0) that I should aim to run my own crawler only on those sites that get censored by other, mainstream, search engines and the rest of the sites should be accessible through other search engines, including the site "built in search engines" like the search line of the [arXiv](https://arxiv.org/). 

If one needs privacy for searching the arXiv, then one should use the Tor or [TorBrowser](https://www.torproject.org/projects/torbrowser.html.en). What regards to censorship, then censorship of the arXiv search line does not make sense, because the arXiv runners can just delete documents from their collection. That means, it's OK to trust their search results, exept when one has the capability to make a mirror copy of their whole document collection. That is to say, there is no inherent need to index documents that are served by public collections, except when one wants personalization. 

I suggest that You offer an API subscription service, where privacy is assured by selling one-time-use query tickets for bitcoins. One ticket for one query. To allow Your clients to swap tickets in a mixnet fashion, people must be able to verify, whether a ticket is valid, without using up the ticket and without having the ticket. A ticket might consist of a single, long, serial number, where the first 20 digits are a validity verification code and to use the paid API, a the whole serial number must be bundled with the query. Tickets are single-use items, id est after the serial number has been submitted, it can not be used any more. 

The price should not be more than 10€ per year per person, which should contain 

    365_days * 100_queries_per_day = 36500_queries === 36500_tickets_for_the_10EUR

A 5€ bundle, with halve as many tickets, should also be available.  The public site might be then add-driven, but the paid-for tickets would return advertisement free results and ONLY THOSE RESULTS that are IN YOUR SERVERS.

I think that a 1€ bundle might be a good sales item, specially in a form of a special mobile application that wraps Your search engine and other search engines. The mobile app version won't be private, but it can be relatively censorship free and use onion-encrypted connection that uses a key that You send to the person in a form of a series of QR-codes by using snail-mail. The "authorities" will, of cource, try to intercept those paper-letters, but due to the onion-encryption they have to intercept ALL snail-mails to get ALL QR-codes. 

Of course, i'ts all easier said than done :-D

Thank You for reading my comment.
