### ISSUE TITLE
Method POST instead of GET?

### ISSUE THREAD

**Issue by zmni** [privacore/open-source-search-engine#58]
Imo, this should be the default method, and a setting option to toggle to GET. All other _privacy_ search engines have this option built in. Please add this feature. Thanks.

**Comment by martinvahi** [comment]
I'm NOT a Privacore developer, NOR am I active at the
Privacore open source side, but I just want to comment that
although I do not know, whether the https protocol reveals
the GET method related extra parameters at the URL, the 
advantage of the POST method at NON-private use cases
over GET method is that POST method does not have the
kind of size restrictions that GET method has. That's why
AJAX libraries are better off by using POST in stead of GET.

Thank You for reading my comment :-)
